/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paineis;

import java.awt.CardLayout;

/**
 *
 * @author mcn
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Root = new javax.swing.JPanel();
        PainelPrincipal = new javax.swing.JPanel();
        bPrincipalB = new javax.swing.JButton();
        bPrincipalC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PainelB = new javax.swing.JPanel();
        bPainelBPrincipal = new javax.swing.JButton();
        bPainelBPainelC = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PainelC = new javax.swing.JPanel();
        bPainelCPainelB = new javax.swing.JButton();
        bPainelCPrincipal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Root.setLayout(new java.awt.CardLayout());

        PainelPrincipal.setBackground(new java.awt.Color(204, 255, 204));

        bPrincipalB.setText("Painel B");
        bPrincipalB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrincipalBActionPerformed(evt);
            }
        });

        bPrincipalC.setText("Painel C");
        bPrincipalC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrincipalCActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Painel Inicial");

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipalLayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bPrincipalB, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(bPrincipalC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(bPrincipalB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(bPrincipalC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        Root.add(PainelPrincipal, "principal");

        PainelB.setBackground(new java.awt.Color(255, 204, 204));

        bPainelBPrincipal.setText("Principal");
        bPainelBPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPainelBPrincipalActionPerformed(evt);
            }
        });

        bPainelBPainelC.setText("Painel C");
        bPainelBPainelC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPainelBPainelCActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel2.setText("Você esta no Painel B");

        javax.swing.GroupLayout PainelBLayout = new javax.swing.GroupLayout(PainelB);
        PainelB.setLayout(PainelBLayout);
        PainelBLayout.setHorizontalGroup(
            PainelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBLayout.createSequentialGroup()
                .addGroup(PainelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelBLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel2))
                    .addGroup(PainelBLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(PainelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bPainelBPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(bPainelBPainelC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        PainelBLayout.setVerticalGroup(
            PainelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(bPainelBPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(bPainelBPainelC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        Root.add(PainelB, "painelB");

        PainelC.setBackground(new java.awt.Color(0, 255, 204));

        bPainelCPainelB.setText("Painel B");
        bPainelCPainelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPainelCPainelBActionPerformed(evt);
            }
        });

        bPainelCPrincipal.setText("Principal");
        bPainelCPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPainelCPrincipalActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel3.setText("Você está no Painel C");

        javax.swing.GroupLayout PainelCLayout = new javax.swing.GroupLayout(PainelC);
        PainelC.setLayout(PainelCLayout);
        PainelCLayout.setHorizontalGroup(
            PainelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCLayout.createSequentialGroup()
                .addGap(0, 194, Short.MAX_VALUE)
                .addGroup(PainelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCLayout.createSequentialGroup()
                        .addGroup(PainelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bPainelCPainelB, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(bPainelCPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(184, 184, 184))))
        );
        PainelCLayout.setVerticalGroup(
            PainelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addGap(51, 51, 51)
                .addComponent(bPainelCPainelB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(bPainelCPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        Root.add(PainelC, "painelC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Root, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Root, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPrincipalBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrincipalBActionPerformed
        
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root, "painelB");
        
    }//GEN-LAST:event_bPrincipalBActionPerformed

    private void bPrincipalCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrincipalCActionPerformed
        
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root, "painelC");
        
    }//GEN-LAST:event_bPrincipalCActionPerformed

    private void bPainelBPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPainelBPrincipalActionPerformed
        
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root, "principal");
        
    }//GEN-LAST:event_bPainelBPrincipalActionPerformed

    private void bPainelBPainelCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPainelBPainelCActionPerformed
        
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root, "painelC");
        
    }//GEN-LAST:event_bPainelBPainelCActionPerformed

    private void bPainelCPainelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPainelCPainelBActionPerformed
       
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root, "painelB");
        
    }//GEN-LAST:event_bPainelCPainelBActionPerformed

    private void bPainelCPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPainelCPrincipalActionPerformed
       
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root, "principal");
        
    }//GEN-LAST:event_bPainelCPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelB;
    private javax.swing.JPanel PainelC;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel Root;
    private javax.swing.JButton bPainelBPainelC;
    private javax.swing.JButton bPainelBPrincipal;
    private javax.swing.JButton bPainelCPainelB;
    private javax.swing.JButton bPainelCPrincipal;
    private javax.swing.JButton bPrincipalB;
    private javax.swing.JButton bPrincipalC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
